import { createAccount, createClient } from 'https://esm.sh/genlayer-js@1.1.8';
import { studionet } from 'https://esm.sh/genlayer-js@1.1.8/chains';

const CONTRACT='0x39708dd0A20512E7dF30EB24Bba12B13E39bD0c5';
const ENDPOINT='https://studio.genlayer.com/api';
const SOURCES=['https://raw.githubusercontent.com/sanshos1/guild-passport/4bc4e038d6ab51686a1a331cefe17c66a8a077a7/evidence/registry.txt','https://cdn.jsdelivr.net/gh/sanshos1/guild-passport@4bc4e038d6ab51686a1a331cefe17c66a8a077a7/evidence/credential.txt'];
const reader=createClient({chain:studionet,endpoint:ENDPOINT,account:createAccount()});
let wallet,account;

const app=document.createElement('div');
app.className='gp-app';
app.innerHTML=`
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap');
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07130f;color:#f4f1e7;font:16px 'DM Sans',sans-serif}
.gp-app{min-height:100vh;background:radial-gradient(circle at 78% 8%,#254638 0,transparent 27%),#07130f;display:grid;grid-template-columns:236px 1fr}
.gp-side{position:sticky;top:0;height:100vh;padding:28px 20px;border-right:1px solid #294239;background:#091712;display:flex;flex-direction:column}
.gp-brand{display:flex;align-items:center;gap:12px;font:800 1.05rem Manrope,sans-serif}.gp-mark{width:42px;height:48px;border:1px solid #ddb85a;border-radius:8px 8px 16px 16px;display:grid;place-items:center;color:#ddb85a}
.gp-nav{display:grid;gap:6px;margin-top:52px}.gp-nav button{border:0;background:transparent;color:#93a59d;padding:13px 14px;text-align:left;border-radius:10px;font:600 .95rem inherit;cursor:pointer}.gp-nav button.active,.gp-nav button:hover{background:#193027;color:#fff}.gp-nav button.active{box-shadow:inset 3px 0 #ddb85a}
.network{margin-top:auto;border:1px solid #294239;border-radius:12px;padding:14px;color:#a9b8b1;font-size:.85rem}.live-dot{display:inline-block;width:8px;height:8px;background:#5ce89a;border-radius:50%;margin-right:8px;box-shadow:0 0 0 0 #5ce89a;animation:pulse 2s infinite}
.gp-main{padding:28px 32px 48px;min-width:0}.topbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}.eyebrow{color:#96a79f;font-size:.78rem;letter-spacing:.14em;text-transform:uppercase}.topbar h1{font:800 clamp(1.8rem,3vw,2.6rem) Manrope;margin:.2rem 0}
.wallet{border:1px solid #ddb85a;background:#ddb85a;color:#07130f;border-radius:12px;padding:12px 18px;font-weight:800;cursor:pointer}.wallet:hover{background:#f5d77e}
.view{display:none}.view.active{display:block;animation:rise .45s ease both}
.summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:18px}.stat{border:1px solid #294239;border-radius:16px;background:#0d1e18;padding:18px}.stat b{font:800 2rem Manrope;display:block;margin-top:8px}.stat small{color:#91a49b}
.dashboard-grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(320px,.8fr);gap:18px}.panel{border:1px solid #294239;background:#0d1e18;border-radius:18px;overflow:hidden}.panel-head{padding:18px 20px;border-bottom:1px solid #294239;display:flex;justify-content:space-between;align-items:center}.panel-head h2{font:700 1.05rem Manrope;margin:0}.panel-head span{color:#8ea198;font-size:.82rem}
.passport-stage{padding:28px;min-height:390px;display:grid;place-items:center;background:linear-gradient(135deg,#10271e,#0b1914)}
.passport-card{position:relative;width:min(100%,610px);aspect-ratio:1.68;border-radius:24px;background:linear-gradient(125deg,#f3ead4,#d8c796);color:#15372c;padding:26px;box-shadow:0 30px 70px #0008;overflow:hidden;transform:perspective(1000px) rotateX(1deg) rotateY(-2deg);transition:.35s transform}
.passport-card:hover{transform:perspective(1000px) rotateX(0) rotateY(0) translateY(-4px)}.passport-card:before{content:'';position:absolute;inset:0;background:repeating-linear-gradient(118deg,transparent 0 18px,#fff2 19px 20px);pointer-events:none}
.scan{position:absolute;inset:0 auto 0 -25%;width:18%;background:linear-gradient(90deg,transparent,#fff8,transparent);transform:skewX(-16deg);animation:scan 4.5s ease-in-out infinite}
.card-top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #43635966;padding-bottom:12px}.card-top b{font:800 1rem Manrope}.chip{width:48px;height:36px;border:1px solid #95792f;border-radius:7px;background:linear-gradient(90deg,transparent 45%,#95792f 46% 50%,transparent 51%),linear-gradient(#cfae52 45%,#95792f 46% 50%,#cfae52 51%)}
.credential{display:grid;grid-template-columns:120px 1fr;gap:22px;margin-top:22px}.portrait{aspect-ratio:.78;border-radius:14px;background:linear-gradient(160deg,#183f32,#2f715a);display:grid;place-items:center;color:#e7cd7a;font:800 2.3rem Manrope}.data-row{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-bottom:14px}.datum small{display:block;color:#567067;font-size:.68rem;letter-spacing:.12em}.datum b{font:700 .96rem Manrope}
.card-foot{position:absolute;left:26px;right:26px;bottom:20px;display:flex;justify-content:space-between;align-items:end}.machine{font:600 .72rem ui-monospace;letter-spacing:.12em}.verified-seal{width:90px;height:90px;border:4px double #a02f2b;border-radius:50%;display:grid;place-items:center;text-align:center;color:#a02f2b;font:800 .75rem Manrope;transform:rotate(-11deg);opacity:.18;transition:.5s}.verified-seal.on{opacity:1;animation:stamp .55s cubic-bezier(.2,1.7,.3,1)}
.activity{display:grid}.activity-item{display:grid;grid-template-columns:12px 1fr auto;gap:12px;padding:17px 20px;border-bottom:1px solid #22382f}.activity-item:last-child{border:0}.activity-item i{width:10px;height:10px;background:#ddb85a;border-radius:50%;margin-top:5px}.activity-item strong{display:block;font-size:.9rem}.activity-item small,.activity-item time{color:#83968d;font-size:.76rem}.activity-item time{white-space:nowrap}
.issue-layout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px}.form-panel{padding:24px}.form-panel h2{font:700 1.4rem Manrope;margin:0 0 22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:grid;gap:7px}.field.full{grid-column:1/-1}.field span{font-size:.8rem;color:#a8b8b0}.field input,.field select{width:100%;border:1px solid #345045;background:#091712;color:#fff;border-radius:11px;padding:13px;font:inherit}.field input:focus,.field select:focus{outline:2px solid #ddb85a;outline-offset:1px}
.evidence-box{grid-column:1/-1;border:1px dashed #486257;border-radius:13px;padding:15px;display:flex;justify-content:space-between;gap:20px}.evidence-box b{display:block}.evidence-box small{color:#8fa198}.evidence-count{color:#5ce89a;font-weight:800}
.flow{display:grid;gap:10px;margin-top:22px}.flow button{border:1px solid #345045;background:#142820;color:#fff;border-radius:11px;padding:13px;text-align:left;font-weight:700;cursor:pointer}.flow button:hover{border-color:#ddb85a;background:#1b352a}.flow button.primary{background:#ddb85a;color:#07130f;border-color:#ddb85a}
.status-panel{padding:22px}.status-panel h3{font:700 1rem Manrope;margin:0}.timeline{margin:22px 0;display:grid;gap:0}.stage{display:grid;grid-template-columns:32px 1fr;gap:10px;min-height:66px}.stage-dot{width:22px;height:22px;border:1px solid #557067;border-radius:50%;display:grid;place-items:center;font-size:.7rem;position:relative}.stage:not(:last-child) .stage-dot:after{content:'';position:absolute;top:22px;width:1px;height:44px;background:#3b554a}.stage.current .stage-dot{background:#ddb85a;border-color:#ddb85a;color:#07130f}.stage b{display:block;font-size:.85rem}.stage small{color:#84978e}.console{background:#07130f;border-radius:12px;padding:15px;min-height:112px;color:#77f0aa;font:13px/1.5 ui-monospace;white-space:pre-wrap}
.registry-tools{display:flex;gap:12px;margin-bottom:16px}.registry-tools input{flex:1;border:1px solid #345045;background:#0d1e18;color:#fff;border-radius:12px;padding:13px}.registry-table{width:100%;border-collapse:collapse}.registry-table th,.registry-table td{padding:16px 18px;border-bottom:1px solid #294239;text-align:left}.registry-table th{color:#8fa198;font-size:.74rem;letter-spacing:.08em}.pill{display:inline-flex;padding:5px 9px;border-radius:99px;background:#163b2b;color:#64e8a0;font-size:.75rem}.pill.pending{background:#3a3117;color:#f0cb65}.inspect{border:0;background:transparent;color:#ddb85a;cursor:pointer;font-weight:700}
.empty-note{padding:22px;color:#83968d}
@keyframes pulse{70%{box-shadow:0 0 0 8px #5ce89a00}}@keyframes scan{0%,25%{left:-25%}70%,100%{left:120%}}@keyframes stamp{0%{transform:scale(2.2) rotate(-25deg);opacity:0}100%{transform:scale(1) rotate(-11deg);opacity:1}}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
@media(max-width:980px){.gp-app{grid-template-columns:76px 1fr}.gp-brand span,.gp-nav button span,.network span{display:none}.gp-side{padding:20px 12px}.gp-mark{margin:auto}.gp-nav button{text-align:center}.dashboard-grid,.issue-layout{grid-template-columns:1fr}.summary{grid-template-columns:1fr 1fr 1fr}}
@media(max-width:680px){.gp-app{display:block}.gp-side{position:sticky;z-index:10;width:100%;height:auto;display:flex;flex-direction:row;align-items:center;padding:10px 14px;border-right:0;border-bottom:1px solid #294239}.gp-mark{width:34px;height:38px;margin:0}.gp-brand{margin-right:auto}.gp-nav{display:flex;margin:0}.gp-nav button{padding:10px}.network{display:none}.gp-main{padding:20px 14px}.topbar{align-items:flex-start}.topbar h1{font-size:1.55rem}.wallet{padding:10px 12px}.summary{grid-template-columns:1fr}.passport-stage{padding:14px;min-height:330px}.passport-card{aspect-ratio:auto;min-height:320px;padding:18px}.credential{grid-template-columns:78px 1fr;gap:14px}.data-row{grid-template-columns:1fr}.card-foot{left:18px;right:18px}.verified-seal{width:70px;height:70px}.form-grid{grid-template-columns:1fr}.field.full,.evidence-box{grid-column:auto}.registry-table th:nth-child(3),.registry-table td:nth-child(3){display:none}}
</style>
<aside class="gp-side"><div class="gp-brand"><div class="gp-mark">GP</div><span>Guild Passport</span></div><nav class="gp-nav" aria-label="Workspace"><button class="active" data-view="dashboard">◫ <span>Overview</span></button><button data-view="issue">＋ <span>Issue passport</span></button><button data-view="registry">⌕ <span>Registry</span></button></nav><div class="network"><span class="live-dot"></span><b>StudioNet</b><br><span>Registry is responding</span></div></aside>
<main class="gp-main"><header class="topbar"><div><div class="eyebrow">Source-bound credential registry</div><h1 id="page-title">Passport overview</h1></div><button class="wallet" id="cx">Present wallet</button></header>
<section class="view active" id="dashboard"><div class="summary"><div class="stat"><small>Active passports</small><b>128</b><small>+12 this epoch</small></div><div class="stat"><small>Verified issuers</small><b>14</b><small>Across 6 guilds</small></div><div class="stat"><small>Revocations</small><b>03</b><small>All source-bound</small></div></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>Credential preview</h2><span>GP-8841</span></div><div class="passport-stage"><article class="passport-card"><div class="scan"></div><div class="card-top"><b>GENLAYER GUILD PASSPORT</b><div class="chip"></div></div><div class="credential"><div class="portrait">AK</div><div><div class="data-row"><div class="datum"><small>SUBJECT</small><b>0x7C2A...91F0</b></div><div class="datum"><small>CLASS</small><b>BUILDER</b></div></div><div class="data-row"><div class="datum"><small>ISSUER</small><b>ATLAS GUILD</b></div><div class="datum"><small>STATUS</small><b>ACTIVE</b></div></div></div></div><div class="card-foot"><div class="machine">GP8841&lt;&lt;BUILDER&lt;&lt;ACTIVE</div><div class="verified-seal on">SOURCE<br>VERIFIED</div></div></article></div></section>
<aside class="panel"><div class="panel-head"><h2>Registry activity</h2><span>Live</span></div><div class="activity"><div class="activity-item"><i></i><div><strong>Passport activated</strong><small>GP-8841 · Builder</small></div><time>2m</time></div><div class="activity-item"><i></i><div><strong>Subject consented</strong><small>GP-8839 · Reviewer</small></div><time>18m</time></div><div class="activity-item"><i></i><div><strong>Issuer authorized</strong><small>Northstar Guild</small></div><time>1h</time></div><div class="activity-item"><i></i><div><strong>Passport revoked</strong><small>GP-8812 · Maintainer</small></div><time>3h</time></div></div></aside></div></section>
<section class="view" id="issue"><div class="issue-layout"><section class="panel form-panel"><h2>New passport application</h2><div class="form-grid"><label class="field"><span>Passport number</span><input id="id" value="GP-NEW"></label><label class="field"><span>Subject address</span><input id="subject" placeholder="0x..."></label><label class="field full"><span>Credential class</span><select id="kind"><option>Builder</option><option>Reviewer</option><option>Maintainer</option></select></label><div class="evidence-box"><div><b>Evidence bundle</b><small>Guild registry and credential attestation are pinned.</small></div><div class="evidence-count">2 / 2 ready</div></div></div><div class="flow"><button id="authorize">Authorize current wallet as issuer</button><button id="draft" class="primary">Create passport draft</button><button id="consent">Record subject consent</button><button id="activate">Verify evidence and activate</button><button id="revoke">Revoke passport</button></div></section>
<aside class="panel status-panel"><h3>Application lifecycle</h3><div class="timeline"><div class="stage current"><div class="stage-dot">1</div><div><b>Draft</b><small>Identity and class</small></div></div><div class="stage"><div class="stage-dot">2</div><div><b>Consent</b><small>Subject approval</small></div></div><div class="stage"><div class="stage-dot">3</div><div><b>Evidence review</b><small>Independent sources</small></div></div><div class="stage"><div class="stage-dot">4</div><div><b>Active</b><small>Canonical credential</small></div></div></div><output class="console" id="state">Application desk ready.</output></aside></div></section>
<section class="view" id="registry"><div class="registry-tools"><input id="search" placeholder="Search passport, subject or class"><button class="wallet" id="lookup">Read contract</button></div><section class="panel"><table class="registry-table"><thead><tr><th>PASSPORT</th><th>SUBJECT</th><th>CLASS</th><th>STATUS</th><th></th></tr></thead><tbody id="records"><tr><td>GP-8841</td><td>0x7C2A...91F0</td><td>Builder</td><td><span class="pill">Active</span></td><td><button class="inspect" data-id="GP-8841">Inspect</button></td></tr><tr><td>GP-8839</td><td>0xA440...09B2</td><td>Reviewer</td><td><span class="pill pending">Consent</span></td><td><button class="inspect" data-id="GP-8839">Inspect</button></td></tr><tr><td>GP-8812</td><td>0x31E8...B617</td><td>Maintainer</td><td><span class="pill">Revoked</span></td><td><button class="inspect" data-id="GP-8812">Inspect</button></td></tr></tbody></table><div class="empty-note" id="registry-state">Select a passport to read its canonical onchain state.</div></section></section>
</main>`;
document.body.replaceChildren(app);

const q=s=>app.querySelector(s), value=id=>q('#'+id)?.value.trim()||'';
const stringify=x=>typeof x==='string'?x:JSON.stringify(x,(_,z)=>typeof z==='bigint'?z.toString():z,2);
const show=x=>{q('#state').textContent=stringify(x)};
function openView(name){app.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));app.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));q('#page-title').textContent={dashboard:'Passport overview',issue:'Issue a passport',registry:'Credential registry'}[name]}
app.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>openView(button.dataset.view));

async function connect(){const p=window.ethereum;if(!p)throw Error('Install MetaMask or Rabby.');[account]=await p.request({method:'eth_requestAccounts'});if(String(await p.request({method:'eth_chainId'})).toLowerCase()!=='0xf22f')await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0xf22f'}]});wallet=createClient({chain:studionet,endpoint:ENDPOINT,account,provider:p});q('#cx').textContent=account.slice(0,6)+'...'+account.slice(-4);if(!value('subject'))q('#subject').value=account;show('Wallet connected to StudioNet.')}
async function readPassport(id=value('id')){const result=await reader.readContract({address:CONTRACT,functionName:'get_passport',args:[id]});return result}
async function load(){const result=await readPassport();show(result);return result}
async function act(fn,args){try{if(!wallet)await connect();show('Approval requested: '+fn);const hash=await wallet.writeContract({address:CONTRACT,functionName:fn,args,value:0n});show('Submitted '+hash+'. Waiting for validator acceptance...');await wallet.waitForTransactionReceipt({hash,status:'ACCEPTED',retries:120,interval:5000});const result=await load();show(result);if(fn==='activate'){app.querySelector('.verified-seal').classList.remove('on');requestAnimationFrame(()=>app.querySelector('.verified-seal').classList.add('on'))}}catch(error){show(error.message||String(error))}}
q('#cx').onclick=()=>connect().catch(error=>show(error.message||String(error)));
q('#authorize').onclick=()=>act('authorize_issuer',[account||value('subject'),true]);
q('#draft').onclick=()=>act('draft',[value('id'),value('subject'),value('kind'),SOURCES]);
q('#consent').onclick=()=>act('consent',[value('id')]);
q('#activate').onclick=()=>act('activate',[value('id')]);
q('#revoke').onclick=()=>act('revoke',[value('id')]);
q('#lookup').onclick=async()=>{try{q('#registry-state').textContent=stringify(await readPassport(value('search')))}catch(error){q('#registry-state').textContent=error.message||String(error)}};
app.querySelectorAll('.inspect').forEach(button=>button.onclick=async()=>{q('#search').value=button.dataset.id;try{q('#registry-state').textContent=stringify(await readPassport(button.dataset.id))}catch(error){q('#registry-state').textContent=error.message||String(error)}});
q('#search').oninput=()=>{const term=value('search').toLowerCase();q('#records').querySelectorAll('tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(term))};
